#!/bin/bash
eww="$HOME/eww/target/release/eww"
colorschemes=$(ls $HOME/.config/colorscheme/)
colorscheme_list=""
for value in $colorschemes
  do
    if [[ $value != "current-colorscheme" ]] ; then
      colorscheme_list+="$value\n"
    fi
  done

val=$(printf "$colorscheme_list" | rofi -dmenu -no-custom -p 'Colorschemes :')
echo $val
if [[ $val ]] ; then
  cp "$HOME/.config/colorscheme/${val}/${val}.css" $HOME/.config/colorscheme/current-colorscheme/current-colorscheme.css 2> /dev/null
  cp "$HOME/.config/colorscheme/${val}/${val}.rasi" $HOME/.config/colorscheme/current-colorscheme/current-colorscheme.rasi 2> /dev/null
  cp "$HOME/.config/colorscheme/${val}/${val}.conf" $HOME/.config/colorscheme/current-colorscheme/current-colorscheme.conf 2> /dev/null
  $eww reload &
  pkill waybar && waybar
fi
