#!/bin/bash
eww="$HOME/eww/target/release/eww"
wifi_status=$(nmcli r wifi)

if [[ $wifi_status == "enabled" ]] ; then
  switch="off"
else
  switch="on"
fi

if [[ $1 == "control-center" ]] ; then
  $eww close control-center || $eww open control-center 
fi

if [[ $1 == "date" ]] ; then
  $eww close date || $eww open date
fi

if [[ $1 == "wifi-on-off" ]] ; then
  nmcli r wifi $switch
fi
