#!/bin/bash

status="$(playerctl -p spotify,vlc status 2> /dev/null)"
song_title="$(playerctl -p spotify,vlc metadata title 2> /dev/null)"
song_artist="$(playerctl -p spotify,vlc metadata artist 2> /dev/null)"

if [[ -z $status ]] ; then
  class="no-media"
fi
getCoverArt () {
  
  TMP_DIR="$HOME/.cache/eww"
  TMP_COVER="$TMP_DIR/cover.png"
  if [[ ! -d $TMP_DIR ]] ; then
    mkdir -p $TMP_DIR
  fi

  spotify_cover_art="$(playerctl -p spotify metadata mpris:artUrl 2> /dev/null)"
  vlc_cover_art="$(playerctl -p vlc metadata mpris:artUrl 2> /dev/null)"

  if [[ -z $status ]] ; then
    cp ~/.config/eww/assets/no_music.png $TMP_COVER
  elif [[ $spotify_cover_art ]] ; then
    curl -s "$spotify_cover_art" > $TMP_COVER
  elif [[ $vlc_cover_art ]] ; then
    curl -s "$vlc_cover_art" > $TMP_COVER
  fi
  
  echo $TMP_COVER
}

if [[ $1 == "class" ]] ; then
  echo $class
fi

if [[ $status == "Playing" ]] ; then 
  play_pause_icon=""
else
  play_pause_icon=""
fi

if [[ $1 == "play-pause-icon" ]] ; then
  echo $play_pause_icon
fi

if [[ $1 == "next-icon" ]] ; then
  echo "󰙢"
fi

if [[ $1 == "previous-icon" ]] ; then
  echo "󰙤"
fi

if [[ $1 == "song_title" ]] ; then 
  if [[ -z $song_title ]] ; then
    echo "------------"
  else 
    echo $song_title
  fi
fi

if [[ $1 == "song_artist" ]] ; then
  if [[ -z $song_artist ]] ; then
    echo "------"
  else
    echo $song_artist
  fi
fi

if [[ $1 == "getCoverArt" ]] ; then
  getCoverArt
fi

if [[ $1 == "play_pause" ]] ; then
  playerctl play-pause 2> /dev/null
fi

if [[ $1 == "previous" ]] ; then
  playerctl previous 2> /dev/null
fi

if [[ $1 == "next" ]] ; then
  playerctl next 2> /dev/null
fi
